package Tela;
import javax.swing.JOptionPane;
import Main.ContaBancaria;

/**
 *
 * @author Artur
 */
public class Tela extends javax.swing.JFrame {
    static int qtdContas = 0;
    static ContaBancaria[] contas = new ContaBancaria[10];
    /**
     * Creates new form Tela
     */
    public Tela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        campoNumero = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        campoTitular = new javax.swing.JTextField();
        jBtnCadastrar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabelTitularCadastro = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(650, 90));
        setPreferredSize(new java.awt.Dimension(650, 90));
        getContentPane().setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel1.setText("Numero");
        getContentPane().add(jLabel1);

        campoNumero.setMinimumSize(new java.awt.Dimension(80, 22));
        campoNumero.setPreferredSize(new java.awt.Dimension(80, 22));
        getContentPane().add(campoNumero);

        jLabel2.setText("Titular");
        getContentPane().add(jLabel2);

        campoTitular.setMinimumSize(new java.awt.Dimension(71, 22));
        campoTitular.setPreferredSize(new java.awt.Dimension(71, 22));
        getContentPane().add(campoTitular);

        jBtnCadastrar.setText("Cadastrar");
        jBtnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnCadastrar);

        jLabel3.setText("Titular");
        getContentPane().add(jLabel3);
        getContentPane().add(jLabelTitularCadastro);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCadastrarActionPerformed
        String titular = this.campoTitular.getText();
        String numero = this.campoNumero.getText();

        ContaBancaria selecionada = buscar(numero);
        if (selecionada != null) {
            JOptionPane.showMessageDialog(this, "Conta ja cadastrada");
            return;
        }
        selecionada = new ContaBancaria(numero, titular);
        this.jLabelTitularCadastro.setText(selecionada.getTitular());
        contas[qtdContas] = selecionada;
        qtdContas++;
    }//GEN-LAST:event_jBtnCadastrarActionPerformed

    public static ContaBancaria buscar(String numero) {
        if (qtdContas == 0) {
            return null;
        }
        for (ContaBancaria cb : contas) {
            if (cb.getNumero().equals(numero)) {
                return cb;
            }
        }
        return null;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField campoNumero;
    private javax.swing.JTextField campoTitular;
    private javax.swing.JButton jBtnCadastrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelTitularCadastro;
    // End of variables declaration//GEN-END:variables
}

